set_property PACKAGE_PIN Y9 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property PACKAGE_PIN G22 [get_ports reset_n]
set_property IOSTANDARD LVCMOS18 [get_ports reset_n]

set_property PACKAGE_PIN F22 [get_ports up_down]
set_property IOSTANDARD LVCMOS18 [get_ports up_down]

set_property PACKAGE_PIN Y11 [get_ports {seg[0]}]
set_property PACKAGE_PIN AA11 [get_ports {seg[1]}]
set_property PACKAGE_PIN Y10 [get_ports {seg[2]}]
set_property PACKAGE_PIN AA9 [get_ports {seg[3]}]
set_property PACKAGE_PIN W12 [get_ports {seg[4]}]
set_property PACKAGE_PIN W11 [get_ports {seg[5]}]
set_property PACKAGE_PIN V10 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]

set_property PACKAGE_PIN W8 [get_ports digit_select]
set_property IOSTANDARD LVCMOS33 [get_ports digit_select]
